### PR TITLE
Update for using with VSPK 5.0

### PR DESCRIPTION
**Pull request by axxyhtrx**

### CODE REVIEW

**Comment by pdellaert** [comment]
Hi @axxyhtrx , thanks for the contribution. 
Out of curiosity, are you a Nokia/Nuage Networks employee? (that is not required to contribute at all, but i like to keep track :))

**Comment by axxyhtrx** [comment]
Yes, I am =)

**Review by pdellaert — APPROVED** [review]

**Comment by pdellaert** [comment]
@axxyhtrx, Which releases of Nuage and OpenStack did you test this specifically? (i see Pike, but no Nuage release).

**Comment by axxyhtrx** [comment]
> @axxyhtrx, Which releases of Nuage and OpenStack did you test this specifically? (i see Pike, but no Nuage release).

Tested with Pike from Packstack and Nuage 5.3.2

```
[root@controller ~]# rpm -qa | grep nuage
nuage-openstack-heat-9.0.0-5.3.2_20_nuage.noarch
nuage-openstack-neutronclient-6.3.0-5.3.2_20_nuage.noarch
nuage-openstack-neutron-11.0.0-5.3.2_20_nuage.noarch
nuage-metadata-agent-5.3.2-28.el7.x86_64
nuage-openvswitch-5.3.2-28.el7.x86_64
nuage-openstack-horizon-12.0.0-5.3.2_20_nuage.noarch
nuage-libnetwork-5.3.2-20.el7.x86_64

```

**Comment by pdellaert** [comment]
Thanks!

**Pull request merged**
